# Generated by Django 4.2.7 on 2023-11-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_options_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
    ]
